"""added phone number

Revision ID: 4254b5ad862b
Revises: 105ed2e46f0e
Create Date: 2026-05-25 19:39:13.460795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4254b5ad862b'
down_revision: Union[str, Sequence[str], None] = '105ed2e46f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('votes',
    #                 sa.Column('user_id', sa.Integer(), nullable=False),
    #                 sa.Column('post_id', sa.Integer(), nullable=False),
    #                 sa.ForeignKeyConstraint(
    #                     ['post_id'], ['posts.id'], ondelete='CASCADE'),
    #                 sa.ForeignKeyConstraint(
    #                     ['user_id'], ['users.user_id'], ondelete='CASCADE'),
    #                 sa.PrimaryKeyConstraint('user_id', 'post_id')
    #                 )
    op.drop_column('posts', 'phone_number')
    # op.drop_table('votes')
    # ### end Alembic commands ###
